# Generated by Django 4.1.7 on 2023-03-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=256, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('country', models.CharField(max_length=256, unique=True)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('level_of_education', models.CharField(max_length=1000)),
                ('area_of_interest', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VacAndHoneymoonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=256, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=256, unique=True)),
                ('country', models.CharField(max_length=256, unique=True)),
                ('preferred_destination', models.CharField(max_length=256, unique=True)),
                ('num_of_weeks', models.PositiveIntegerField(max_length=256, unique=True)),
                ('start_date', models.CharField(max_length=256, unique=True)),
                ('end_date', models.CharField(max_length=256, unique=True)),
                ('num_of_persons', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
