# Generated by Django 4.1.7 on 2023-03-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteCurvesApp', '0002_alter_vacandhoneymoonregistration_num_of_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='others',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
