# Generated by Django 4.1.7 on 2023-03-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteCurvesApp', '0004_registration_certs_registration_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='registration',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='end_date',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='num_of_persons',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='num_of_weeks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='preferred_destination',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacandhoneymoonregistration',
            name='start_date',
            field=models.CharField(max_length=256),
        ),
    ]
